[package]
name = "sessionman"
version = "0.1.0"
authors = ["Moritz Borcherding <moritz.borcherding@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acl-rs = "0.1.1"
nix = "0.26"
rustbus = "0.3.2"